#!/bin/bash

# Ping timeout in seconds
TIMEOUT=3

SITES="$*"

if [ -z "$SITES" ]; then
	echo "Syntax: $0 <host>, <host>, ..."
	exit 1
fi

function pinghost() {
	HOST="$1"
	ping -c 1 -t "$TIMEOUT" "$1" > /dev/null
}

function urlexists() {
	curl --output /dev/null --silent --head --fail \
		-m "$TIMEOUT" "$1"
}

for s in $SITES; do
	echo "Checking $s ..."
	echo -n "- ping ..."
	if pinghost "$s"; then
		echo "OK"
	else
		echo "NOK"
	fi
	URL="http://$s"
	echo -n "- checking URL "$URL" ..."
	if urlexists "$URL"; then
		echo "OK"
	else
		echo "NOK"
	fi
done
